export { NexusClient } from './client.js';

export type {
  // Client options
  NexusClientOptions,

  // Domain types
  Project,
  CreateProjectInput,
  Agent,
  CreateAgentInput,
  RelevanceProfile,
  FreshnessPreference,
  Decision,
  CreateDecisionInput,
  UpdateDecisionInput,
  SupersedeDecisionInput,
  DecisionListFilters,
  DecisionSource,
  ConfidenceLevel,
  DecisionStatus,
  Alternative,
  DecisionEdge,
  CreateEdgeInput,
  EdgeRelationship,
  Artifact,
  CreateArtifactInput,
  ArtifactType,
  SessionSummary,
  CreateSessionInput,
  Subscription,
  CreateSubscriptionInput,
  NotifyEvent,
  Priority,
  Notification,
  NotificationType,
  Urgency,
  CompileContextInput,
  ContextPackage,
  DistillInput,
  DistilleryResult,
  Contradiction,
  ContradictionStatus,
  ResolveContradictionInput,
  RelevanceFeedback,
  CreateFeedbackInput,
  UsageSignal,
  GraphResult,
  ImpactAnalysis,
  AuditEntry,
  ProjectStats,
  NexusError,
} from './types.js';

export { NexusApiError } from './types.js';
